version: 2.1

commands:
  initialize_step:
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-repo-{{ checksum "requirements.txt" }}
      - run:
          name: Activate virtual environment
          command: echo "source venv/bin/activate" >> $BASH_ENV

jobs:
  build:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-repo-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  test:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - initialize_step
      - run:
          name: Run tests
          command: python3 manage.py test

workflows:
  sample:
    jobs:
      - build
      - test:
          requires:
            - build
