version: 2.1

jobs:
  checkout_and_build:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "."

  test:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - restore_cache:
          keys: 
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: python manage.py test

workflows:
  sample:
    jobs:
      - checkout_and_build
      - test:
          requires:
            - checkout_and_build
