version: 2.1

jobs:
  checkout_and_build:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python3 -m venv venv
      - run:
          name: Activate virtual environment
          command: 
            . venv/bin/activate
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "."

  test:
    docker:
      - image: cimg/python:3.10.3
    steps:
      - restore_cache:
          keys: 
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: hehe
          command: ls -la
      - run:
          name: Activate virtual environment
          command: . venv/bin/activate
      - run:
          name: Run tests
          command: python3 manage.py test

workflows:
  sample:
    jobs:
      - checkout_and_build
      - test:
          requires:
            - checkout_and_build
